#include "espclaw/admin_ui.h"

#include <string.h>

static const char *ESPCLAW_ADMIN_UI =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "  <title>ESPClaw Admin</title>\n"
    "  <style>\n"
    "    :root{color-scheme:light;background:#f5f1e8;color:#1f2933;font-family:ui-sans-serif,system-ui,sans-serif;}\n"
    "    body{margin:0;background:linear-gradient(180deg,#f4efe5 0%,#fffdf9 100%);}\n"
    "    header{padding:24px;background:#12343b;color:#fff7ea;}\n"
    "    main{display:grid;gap:16px;padding:16px;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));}\n"
    "    section{background:#fff;box-shadow:0 8px 24px rgba(18,52,59,.08);border-radius:16px;padding:16px;}\n"
    "    h1,h2{margin:0 0 12px;}\n"
    "    p,li,label,button{line-height:1.5;}\n"
    "    ul{padding-left:18px;margin:0;}\n"
    "    input,select,textarea,button{width:100%;margin-top:8px;padding:10px;border-radius:10px;border:1px solid #c8d2d9;box-sizing:border-box;font:inherit;}\n"
    "    textarea{min-height:220px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;}\n"
    "    button{background:#12343b;color:white;font-weight:600;cursor:pointer;}\n"
    "    button.secondary{background:#6b7f86;}\n"
    "    button.danger{background:#8e3b2e;}\n"
    "    .grid{display:grid;gap:10px;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));}\n"
    "    .panel{border:1px solid #e3e7ea;border-radius:12px;padding:12px;background:#fbfcfd;}\n"
    "    .status{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap;word-break:break-word;}\n"
    "    .app-list button{margin-top:6px;text-align:left;background:#edf3f4;color:#12343b;}\n"
    "    .muted{color:#52616b;font-size:.95rem;}\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <header>\n"
    "    <h1>ESPClaw Admin</h1>\n"
    "    <p>Configure the device, inspect workspace files, and manage dynamic Lua apps from the same local surface.</p>\n"
    "  </header>\n"
    "  <main>\n"
    "    <section>\n"
    "      <h2>Overview</h2>\n"
    "      <div id=\"overview\" class=\"panel status\">Loading status…</div>\n"
    "    </section>\n"
    "    <section>\n"
    "      <h2>Network</h2>\n"
    "      <label>Wi-Fi SSID<input name=\"wifi_ssid\" autocomplete=\"off\" placeholder=\"Provisioned via runtime\"></label>\n"
    "      <label>Provisioning Mode<select><option>BLE</option><option>SoftAP</option></select></label>\n"
    "      <button class=\"secondary\" type=\"button\">Save Network</button>\n"
    "      <p class=\"muted\">Network mutation routes are still pending. This panel is here to keep the final admin layout coherent while the app surface is wired first.</p>\n"
    "    </section>\n"
    "    <section>\n"
    "      <h2>Provider Auth</h2>\n"
    "      <label>Provider<select id=\"auth-provider\"><option value=\"openai_codex\">openai_codex</option><option value=\"openai_compat\">openai_compat</option><option value=\"anthropic_messages\">anthropic_messages</option></select></label>\n"
    "      <label>Model<input id=\"auth-model\" autocomplete=\"off\" placeholder=\"gpt-5.3-codex\"></label>\n"
    "      <label>Base URL<input id=\"auth-base-url\" autocomplete=\"off\" placeholder=\"https://chatgpt.com/backend-api/codex\"></label>\n"
    "      <label>Account Id<input id=\"auth-account-id\" autocomplete=\"off\" placeholder=\"acc_...\"></label>\n"
    "      <label>Access Token<textarea id=\"auth-access-token\" style=\"min-height:120px\"></textarea></label>\n"
    "      <label>Refresh Token<textarea id=\"auth-refresh-token\" style=\"min-height:80px\"></textarea></label>\n"
    "      <div class=\"grid\">\n"
    "        <button id=\"save-auth\" type=\"button\">Save Auth</button>\n"
    "        <button id=\"import-codex-cli\" type=\"button\" class=\"secondary\">Import Codex CLI</button>\n"
    "        <button id=\"clear-auth\" type=\"button\" class=\"danger\">Clear Auth</button>\n"
    "      </div>\n"
    "      <div id=\"auth-status\" class=\"panel status\">Loading auth…</div>\n"
    "    </section>\n"
    "    <section>\n"
    "      <h2>Workspace</h2>\n"
    "      <div id=\"workspace-files\" class=\"panel status\">Loading workspace…</div>\n"
    "    </section>\n"
    "    <section>\n"
    "      <h2>Tools</h2>\n"
    "      <button id=\"refresh-tools\" type=\"button\" class=\"secondary\">Refresh Tools</button>\n"
    "      <div id=\"tools-list\" class=\"panel status\">Loading tools…</div>\n"
    "    </section>\n"
    "    <section style=\"grid-column:span 2;\">\n"
    "      <h2>Apps</h2>\n"
    "      <div class=\"grid\">\n"
    "        <div class=\"panel\">\n"
    "          <label>App Id<input id=\"app-id\" name=\"app_id\" autocomplete=\"off\" placeholder=\"hello_app\"></label>\n"
    "          <label>Trigger<input id=\"app-trigger\" value=\"manual\" autocomplete=\"off\"></label>\n"
    "          <label>Run Payload<input id=\"app-payload\" autocomplete=\"off\" placeholder=\"payload passed to handle(trigger, payload)\"></label>\n"
    "          <div class=\"grid\">\n"
    "            <button id=\"load-app\" type=\"button\" class=\"secondary\">Load App</button>\n"
    "            <button id=\"new-app\" type=\"button\">Create App</button>\n"
    "            <button id=\"save-app\" type=\"button\">Save Source</button>\n"
    "            <button id=\"run-app\" type=\"button\" class=\"secondary\">Run App</button>\n"
    "            <button id=\"delete-app\" type=\"button\" class=\"danger\">Remove App</button>\n"
    "          </div>\n"
    "          <p class=\"muted\">Create writes a scaffold to `/workspace/apps/&lt;app_id&gt;/`. Save updates the current entrypoint source. Run posts the payload field to the app runtime.</p>\n"
    "        </div>\n"
    "        <div class=\"panel app-list\">\n"
    "          <strong>Installed Apps</strong>\n"
    "          <div id=\"app-list\" class=\"status\">Loading apps…</div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <label>Lua Source<textarea id=\"app-source\">function handle(trigger, payload)\n  return \"ok\"\nend\n</textarea></label>\n"
    "      <div id=\"app-result\" class=\"panel status\">App actions will appear here.</div>\n"
    "    </section>\n"
    "    <section style=\"grid-column:span 2;\">\n"
    "      <h2>Control Loops</h2>\n"
    "      <div class=\"grid\">\n"
    "        <div class=\"panel\">\n"
    "          <label>Loop Id<input id=\"loop-id\" autocomplete=\"off\" placeholder=\"balance_loop\"></label>\n"
    "          <label>App Id<input id=\"loop-app-id\" autocomplete=\"off\" placeholder=\"balance_bot\"></label>\n"
    "          <label>Trigger<input id=\"loop-trigger\" value=\"manual\" autocomplete=\"off\"></label>\n"
    "          <label>Payload<input id=\"loop-payload\" autocomplete=\"off\" placeholder=\"step input payload\"></label>\n"
    "          <div class=\"grid\">\n"
    "            <label>Period (ms)<input id=\"loop-period\" type=\"number\" min=\"1\" value=\"20\"></label>\n"
    "            <label>Iterations<input id=\"loop-iterations\" type=\"number\" min=\"0\" value=\"0\"></label>\n"
    "          </div>\n"
    "          <div class=\"grid\">\n"
    "            <button id=\"start-loop\" type=\"button\">Start Loop</button>\n"
    "            <button id=\"stop-loop\" type=\"button\" class=\"danger\">Stop Loop</button>\n"
    "            <button id=\"refresh-loops\" type=\"button\" class=\"secondary\">Refresh Loops</button>\n"
    "          </div>\n"
    "          <p class=\"muted\">Loops keep a persistent Lua VM alive and call `handle(trigger, payload)` on a fixed period. Use `iterations=0` for an open-ended loop.</p>\n"
    "        </div>\n"
    "        <div class=\"panel\">\n"
    "          <strong>Loop Status</strong>\n"
    "          <div id=\"loop-list\" class=\"status\">Loading loops…</div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div id=\"loop-result\" class=\"panel status\">Loop actions will appear here.</div>\n"
    "    </section>\n"
    "    <section>\n"
      "      <h2>Telegram</h2>\n"
    "      <label>Polling Interval<input name=\"poll_interval\" value=\"3\"></label>\n"
    "      <label>Allowlist<textarea rows=\"4\"></textarea></label>\n"
    "      <button class=\"secondary\" type=\"button\">Save Channel</button>\n"
    "    </section>\n"
    "    <section>\n"
      "      <h2>Logs & OTA</h2>\n"
    "      <ul><li>Current version</li><li>Pending image</li><li>Rollback state</li></ul>\n"
    "      <button class=\"secondary\" type=\"button\">Upload Firmware</button>\n"
    "    </section>\n"
    "    <section style=\"grid-column:span 2;\">\n"
    "      <h2>Chat</h2>\n"
    "      <label>Session Id<input id=\"chat-session-id\" autocomplete=\"off\" value=\"admin\"></label>\n"
    "      <label>Message<textarea id=\"chat-input\" style=\"min-height:120px\">Inspect the current workspace and tell me what apps are installed.</textarea></label>\n"
    "      <div class=\"grid\">\n"
    "        <button id=\"run-chat\" type=\"button\">Run Chat</button>\n"
    "        <button id=\"load-session\" type=\"button\" class=\"secondary\">Load Session</button>\n"
    "      </div>\n"
    "      <div id=\"chat-result\" class=\"panel status\">Chat runs will appear here.</div>\n"
    "      <div id=\"chat-session\" class=\"panel status\">Session transcript will appear here.</div>\n"
    "    </section>\n"
    "  </main>\n"
    "  <script>\n"
    "    const $ = (id) => document.getElementById(id);\n"
    "    async function fetchJson(url, options) {\n"
    "      const response = await fetch(url, options);\n"
    "      const text = await response.text();\n"
    "      try { return { ok: response.ok, status: response.status, data: JSON.parse(text) }; }\n"
    "      catch (error) { return { ok: response.ok, status: response.status, data: { raw: text, parse_error: String(error) } }; }\n"
    "    }\n"
    "    function showObject(target, value) {\n"
    "      target.textContent = JSON.stringify(value, null, 2);\n"
    "    }\n"
    "    function currentAppId() {\n"
    "      return $('app-id').value.trim();\n"
    "    }\n"
    "    function syncLoopAppId() {\n"
    "      if (!$('loop-app-id').value.trim()) {\n"
    "        $('loop-app-id').value = currentAppId();\n"
    "      }\n"
    "    }\n"
    "    async function loadStatus() {\n"
    "      const result = await fetchJson('/api/status');\n"
    "      showObject($('overview'), result.data);\n"
    "    }\n"
    "    async function loadWorkspace() {\n"
    "      const result = await fetchJson('/api/workspace/files');\n"
    "      showObject($('workspace-files'), result.data);\n"
    "    }\n"
    "    async function loadTools() {\n"
    "      const result = await fetchJson('/api/tools');\n"
    "      showObject($('tools-list'), result.data);\n"
    "    }\n"
    "    async function loadAuth() {\n"
    "      const result = await fetchJson('/api/auth/status');\n"
    "      const profile = result.data || {};\n"
    "      $('auth-provider').value = profile.provider_id || 'openai_codex';\n"
    "      $('auth-model').value = profile.model || '';\n"
    "      $('auth-base-url').value = profile.base_url || '';\n"
    "      $('auth-account-id').value = profile.account_id || '';\n"
    "      if (typeof profile.access_token === 'string') {\n"
    "        $('auth-access-token').value = profile.access_token;\n"
    "      }\n"
    "      if (typeof profile.refresh_token === 'string') {\n"
    "        $('auth-refresh-token').value = profile.refresh_token;\n"
    "      }\n"
    "      showObject($('auth-status'), result.data);\n"
    "    }\n"
    "    async function saveAuth() {\n"
    "      const payload = {\n"
    "        provider_id: $('auth-provider').value,\n"
    "        model: $('auth-model').value.trim(),\n"
    "        base_url: $('auth-base-url').value.trim(),\n"
    "        account_id: $('auth-account-id').value.trim(),\n"
    "        access_token: $('auth-access-token').value.trim(),\n"
    "        refresh_token: $('auth-refresh-token').value.trim(),\n"
    "        source: 'admin'\n"
    "      };\n"
    "      const result = await fetchJson('/api/auth/codex', {\n"
    "        method: 'PUT',\n"
    "        headers: { 'Content-Type': 'application/json; charset=utf-8' },\n"
    "        body: JSON.stringify(payload)\n"
    "      });\n"
    "      showObject($('auth-status'), result.data);\n"
    "      await loadStatus();\n"
    "    }\n"
    "    async function importCodexCli() {\n"
    "      const result = await fetchJson('/api/auth/import-codex-cli', { method: 'POST' });\n"
    "      showObject($('auth-status'), result.data);\n"
    "      if (result.ok) {\n"
    "        await loadAuth();\n"
    "        await loadStatus();\n"
    "      }\n"
    "    }\n"
    "    async function clearAuth() {\n"
    "      const result = await fetchJson('/api/auth/codex', { method: 'DELETE' });\n"
    "      $('auth-access-token').value = '';\n"
    "      $('auth-refresh-token').value = '';\n"
    "      $('auth-account-id').value = '';\n"
    "      showObject($('auth-status'), result.data);\n"
    "      await loadAuth();\n"
    "      await loadStatus();\n"
    "    }\n"
    "    async function loadApps() {\n"
    "      const result = await fetchJson('/api/apps');\n"
    "      const container = $('app-list');\n"
    "      container.innerHTML = '';\n"
    "      const apps = result.data && Array.isArray(result.data.apps) ? result.data.apps : [];\n"
    "      if (apps.length === 0) {\n"
    "        container.textContent = 'No apps installed.';\n"
    "        return;\n"
    "      }\n"
    "      apps.forEach((app) => {\n"
    "        const button = document.createElement('button');\n"
    "        button.type = 'button';\n"
    "        button.textContent = `${app.id} (${app.version})`;\n"
    "        button.addEventListener('click', () => loadApp(app.id));\n"
    "        container.appendChild(button);\n"
    "      });\n"
    "    }\n"
    "    async function loadApp(appId) {\n"
    "      $('app-id').value = appId;\n"
    "      $('loop-app-id').value = appId;\n"
    "      const result = await fetchJson(`/api/apps/detail?app_id=${encodeURIComponent(appId)}`);\n"
    "      if (result.data && result.data.app) {\n"
    "        $('app-source').value = result.data.app.source || '';\n"
    "      }\n"
    "      showObject($('app-result'), result.data);\n"
    "    }\n"
    "    async function createApp() {\n"
    "      const appId = currentAppId();\n"
    "      if (!appId) {\n"
    "        $('app-result').textContent = 'Enter an app id first.';\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/apps/scaffold?app_id=${encodeURIComponent(appId)}`, { method: 'POST' });\n"
    "      showObject($('app-result'), result.data);\n"
    "      await loadApps();\n"
    "      await loadApp(appId);\n"
    "    }\n"
    "    async function saveApp() {\n"
    "      const appId = currentAppId();\n"
    "      if (!appId) {\n"
    "        $('app-result').textContent = 'Enter an app id first.';\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/apps/source?app_id=${encodeURIComponent(appId)}`, {\n"
    "        method: 'PUT',\n"
    "        headers: { 'Content-Type': 'text/plain; charset=utf-8' },\n"
    "        body: $('app-source').value\n"
    "      });\n"
    "      showObject($('app-result'), result.data);\n"
    "      await loadApps();\n"
    "    }\n"
    "    async function runApp() {\n"
    "      const appId = currentAppId();\n"
    "      if (!appId) {\n"
    "        $('app-result').textContent = 'Enter an app id first.';\n"
    "        return;\n"
    "      }\n"
    "      const trigger = $('app-trigger').value.trim() || 'manual';\n"
    "      const result = await fetchJson(`/api/apps/run?app_id=${encodeURIComponent(appId)}&trigger=${encodeURIComponent(trigger)}`, {\n"
    "        method: 'POST',\n"
    "        headers: { 'Content-Type': 'text/plain; charset=utf-8' },\n"
    "        body: $('app-payload').value\n"
    "      });\n"
    "      showObject($('app-result'), result.data);\n"
    "    }\n"
    "    async function loadLoops() {\n"
    "      const result = await fetchJson('/api/loops');\n"
    "      showObject($('loop-list'), result.data);\n"
    "    }\n"
    "    async function startLoop() {\n"
    "      const loopId = $('loop-id').value.trim();\n"
    "      const appId = $('loop-app-id').value.trim() || currentAppId();\n"
    "      if (!loopId || !appId) {\n"
    "        $('loop-result').textContent = 'Enter both loop id and app id first.';\n"
    "        return;\n"
    "      }\n"
    "      const trigger = $('loop-trigger').value.trim() || 'manual';\n"
    "      const periodMs = Number.parseInt($('loop-period').value, 10) || 20;\n"
    "      const iterations = Number.parseInt($('loop-iterations').value, 10) || 0;\n"
    "      const result = await fetchJson(`/api/loops/start?loop_id=${encodeURIComponent(loopId)}&app_id=${encodeURIComponent(appId)}&trigger=${encodeURIComponent(trigger)}&period_ms=${encodeURIComponent(periodMs)}&iterations=${encodeURIComponent(iterations)}`, {\n"
    "        method: 'POST',\n"
    "        headers: { 'Content-Type': 'text/plain; charset=utf-8' },\n"
    "        body: $('loop-payload').value\n"
    "      });\n"
    "      showObject($('loop-result'), result.data);\n"
    "      await loadLoops();\n"
    "    }\n"
    "    async function stopLoop() {\n"
    "      const loopId = $('loop-id').value.trim();\n"
    "      if (!loopId) {\n"
    "        $('loop-result').textContent = 'Enter a loop id first.';\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/loops/stop?loop_id=${encodeURIComponent(loopId)}`, { method: 'POST' });\n"
    "      showObject($('loop-result'), result.data);\n"
    "      await loadLoops();\n"
    "    }\n"
    "    async function deleteApp() {\n"
    "      const appId = currentAppId();\n"
    "      if (!appId) {\n"
    "        $('app-result').textContent = 'Enter an app id first.';\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/apps?app_id=${encodeURIComponent(appId)}`, { method: 'DELETE' });\n"
    "      showObject($('app-result'), result.data);\n"
    "      await loadApps();\n"
    "    }\n"
    "    async function runChat() {\n"
    "      const sessionId = $('chat-session-id').value.trim() || 'admin';\n"
    "      const message = $('chat-input').value;\n"
    "      if (!message.trim()) {\n"
    "        $('chat-result').textContent = 'Enter a chat message first.';\n"
    "        return;\n"
    "      }\n"
    "      const result = await fetchJson(`/api/chat/run?session_id=${encodeURIComponent(sessionId)}`, {\n"
    "        method: 'POST',\n"
    "        headers: { 'Content-Type': 'text/plain; charset=utf-8' },\n"
    "        body: message\n"
    "      });\n"
    "      showObject($('chat-result'), result.data);\n"
    "      await loadChatSession();\n"
    "    }\n"
    "    async function loadChatSession() {\n"
    "      const sessionId = $('chat-session-id').value.trim() || 'admin';\n"
    "      const result = await fetchJson(`/api/chat/session?session_id=${encodeURIComponent(sessionId)}`);\n"
    "      showObject($('chat-session'), result.data);\n"
    "    }\n"
    "    $('load-app').addEventListener('click', () => loadApp(currentAppId()));\n"
    "    $('save-auth').addEventListener('click', saveAuth);\n"
    "    $('import-codex-cli').addEventListener('click', importCodexCli);\n"
    "    $('clear-auth').addEventListener('click', clearAuth);\n"
    "    $('new-app').addEventListener('click', createApp);\n"
    "    $('save-app').addEventListener('click', saveApp);\n"
    "    $('run-app').addEventListener('click', runApp);\n"
    "    $('delete-app').addEventListener('click', deleteApp);\n"
    "    $('start-loop').addEventListener('click', startLoop);\n"
    "    $('stop-loop').addEventListener('click', stopLoop);\n"
    "    $('refresh-loops').addEventListener('click', loadLoops);\n"
    "    $('refresh-tools').addEventListener('click', loadTools);\n"
    "    $('run-chat').addEventListener('click', runChat);\n"
    "    $('load-session').addEventListener('click', loadChatSession);\n"
    "    $('app-id').addEventListener('change', syncLoopAppId);\n"
    "    loadStatus();\n"
    "    loadAuth();\n"
    "    loadWorkspace();\n"
    "    loadTools();\n"
    "    loadApps();\n"
    "    loadLoops();\n"
    "    loadChatSession();\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n";

const char *espclaw_admin_ui_html(void)
{
    return ESPCLAW_ADMIN_UI;
}

size_t espclaw_admin_ui_length(void)
{
    return strlen(ESPCLAW_ADMIN_UI);
}
